server:
  port: 7901
eureka:
  client:
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
spring:
  application:
    name: spring-cloud-consumer-movie
user:
  userPath: http://localhost:7900/simple/