server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
spring:
  application:
    name: spring-cloud-consumer-movie-ribbon
user:
  userPath: http://spring-cloud-provider-user/migu/simple/# VIP virtual ip  虚拟Ip